### ISSUE TITLE
_generate_report function throws deprecation warnings

### ISSUE THREAD

**Issue by wmvanvliet** [neuropycon/ephypype#102]
The `exclude` parameter of [`mne.preprocessing.ICA.plot_sources`](https://mne.tools/stable/generated/mne.preprocessing.ICA.html#mne.preprocessing.ICA.plot_sources) is deprecated, hence the [`preproc._generate_report`](https://github.com/neuropycon/ephypype/blob/master/ephypype/preproc.py#L276) function will not work on MNE-Python version 0.20 and above, and throws deprecation warnings on version 0.19.

**Comment by jasmainak** [comment]
closed by #103
