### ISSUE TITLE
mne.connectivity module, now mne-connectivity library

### ISSUE THREAD

**Issue by alberto-jj** [neuropycon/ephypype#123]
Dear NeuroPycon team,
I just have seen your library and indeed wanted to test the preprocessing pipeline, spectral connectivity on sensor level, and power spectrum analysis notebooks with some resting EEG datasets.
However, after installing NeuroPycon on Google Colab (and Jupyter notebooks as well) I had some errors when importing ephypype.

After running:
`! pip install ephypype`
`! pip install nipype`
`! pip install mne`
`! pip install mne_bids`
`import os.path as op`
`import numpy as np`
`import nipype.pipeline.engine as pe`
`import mne`
`import mne_bids`
`import ephypype`

I get the following error in Colab

> 
> ModuleNotFoundError                       Traceback (most recent call last)
> [<ipython-input-12-e2a04c71f497>](https://localhost:8080/#) in <module>()
> ----> 1 import ephypype
> 
> 4 frames
> [/usr/local/lib/python3.7/dist-packages/ephypype/spectral.py](https://localhost:8080/#) in <module>()
>      10 from scipy.io import savemat
>      11 
> ---> 12 from mne.connectivity import spectral_connectivity
>      13 from mne.viz import circular_layout, plot_connectivity_circle
>      14 
> 
> ModuleNotFoundError: No module named 'mne.connectivity'

- I'm not sure if this might be explained by some changes in MNE (around mid 2021) such as the connectivity measures moved to a separate repository (now  "mne-connectivity" https://mne.tools/mne-connectivity/stable/index.html , instead of previous "mne.connectivity").

I have also tested the above code in Jupyter, obtaining another error, this time on the mne.datasets.utils fetching.
Thus,
`import ephypype`

Gives the following output

> ImportError                               Traceback (most recent call last)
> ~\AppData\Local\Temp/ipykernel_15740/2868412181.py in <module>
> ----> 1 import ephypype
> 
> ~\anaconda3\lib\site-packages\ephypype\__init__.py in <module>
>       1 #from . import interfaces  # noqa
>       2 from . import gather  # noqa
> ----> 3 from . import datasets
>       4 
>       5 from .gather import (gather_conmats, gather_results)
> 
> ~\anaconda3\lib\site-packages\ephypype\datasets.py in <module>
>       7 import os
>       8 import zipfile
> ----> 9 from mne.datasets.utils import _fetch_file
>      10 
>      11 
> 
> ImportError: cannot import name '_fetch_file' from 'mne.datasets.utils' (C:\Users\myuser\anaconda3\lib\site-packages\mne\datasets\utils.py).
> 

The same happened when I tried to import specific functions, or manually import the datasets rather than the whole ephypype library, but it raised the same error in mne.datasets.utils fetching

`from ephypype.nodes import create_iterator, create_datagrabber`
`from ephypype.datasets import fetch_omega_dataset`

Can you kindly let me know if you are aware of these potential issues due to MNE's recent changes? 
I'm relatively new to Python so I'm not able to come up with a solution but I hope this report helps,
Thanks in advance for your help!

**Comment by annapasca** [comment]
Dear @albertoj1107 ,
thanks a lot for your comments and your interest in NeuroPycon!
We are aware about these changes due to last version of MNE wand we are planning to push a new version of NeuroPycon asap.

Have a nice day!
Annalisa
Annalisa

**Comment by luseanevens** [comment]
you can install the MNE version == 0.23, according to the ChangeLog of MNE, the 0.24 update move mne.connectivity to  mne-connectivity.
