### ISSUE TITLE
missing files in docs

### ISSUE THREAD

**Issue by jasmainak** [neuropycon/ephypype#14]
@annapasca you provided me the missing files for the ICA example but these are not the only missing params file. Can you provide us with all the missing param files? Maybe make a pull request. 

Example: https://neuropycon.github.io/neuropycon_doc/examples/preproc_example.html#preproc-example

**Comment by annapasca** [comment]
@jasmainak I pushed all and it seems now there are the files :)
https://neuropycon.github.io/neuropycon_doc/examples/preproc_example.html#preproc-example

**Comment by jasmainak** [comment]
awesome! Thanks @annapasca
