### ISSUE TITLE
Installation with sudo python setup.py develop isn't the best option

### ISSUE THREAD

**Issue by dmalt** [neuropycon/ephypype#3]
We should probably switch to  `pip install --editable .` instead. 
The main difference is that this way of installation delivers an easier way of deleting and updating
packages. It will also track and install all the dependencies. More here:
https://stackoverflow.com/a/15731459

**Comment by annapasca** [comment]
Ok! we have to look at this and change. 
We'd like also to provide an installation by Docker.

**Comment by annapasca** [comment]
we are discussing this issue in #24 #27
