### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by annapasca** [neuropycon/ephypype#42]
Hi @jasmainak !

What is the best way to push files in the gh-pages branch of neuropycon/ephypype? Thks! and no rush :)

**Comment by jasmainak** [comment]
You just need to `$ make install` from the `ephypype/doc` folder. But do it only after the PR is merged. For seeing the output when you make the PR, you can go to the "artifacts" tab in CircleCI

**Comment by annapasca** [comment]
uh thanks! I have just seen in the makefile to see what are the commands to do it.
Thks a lot :)

**Comment by jasmainak** [comment]
@annapasca can we close this issue if your question is answered?
