### ISSUE TITLE
drop support for windows (and python 2?)

### ISSUE THREAD

**Issue by jasmainak** [neuropycon/ephypype#43]
In the last PR of @dmalt we noticed that `nipype` is not really supported on Windows. So, we don't need to have appveyor in that case.

Also, I see that `Travis` is broken on python 2. Is it easy enough to fix @annapasca ? We should keep python 2 support if it's easy. If it's too much work, then we should just update the readme and remove support.

**Comment by annapasca** [comment]
Hi @jasmainak!
I have just seen the Travis error in #38. 
It seems related to the call of `plot_scores` function of `ICA` class of MNE.

![screenshot from 2018-09-28 12-39-48](https://user-images.githubusercontent.com/14320056/46203960-c9161100-c31b-11e8-9477-778ff5d6906c.png)

**Comment by jasmainak** [comment]
okay I see, this seems to be related to the backend. I think the issue is from @dmalt 's pull request where in the [tests](https://github.com/neuropycon/ephypype/blob/master/ephypype/commands/tests/test_cli.py), we don't use the [right matplotlib backend](https://github.com/neuropycon/ephypype/blob/master/ephypype/tests/test_power.py#L3). Could you or @dmalt make a pull request to fix it? Thanks!

**Comment by annapasca** [comment]
thus to fix we have to add `matplotlib.use('Agg')` in `test_cli`?
If so, I can create this PR!

**Comment by dmalt** [comment]
I can create a PR if that's what it takes to fix the error.

**Comment by dmalt** [comment]
I've created a PR https://github.com/neuropycon/ephypype/pull/46. Let's wait to see if Travis and co. are happy

**Comment by jasmainak** [comment]
@dmalt can you also create a pull request to remove appveyor and anything in the documentation which claims we support Windows?

**Comment by jasmainak** [comment]
Thanks!

**Comment by dmalt** [comment]
Ok, I'm on it

**Comment by dmalt** [comment]
@annapasca, how big is the testing data folder?

**Comment by dmalt** [comment]
#49
