### ISSUE TITLE
automatically push documentation to website

### ISSUE THREAD

**Issue by jasmainak** [neuropycon/ephypype#60]
We should automatically push the documentation to github if it builds successfully on CircleCI. That will completely automate the process. Basically, need to do something [like this](https://github.com/mne-tools/mne-bids/blob/master/.circleci/config.yml#L36-L48)

@dmalt maybe you can give it a shot if you have time?

**Comment by jasmainak** [comment]
@annapasca do you want to try this? It would really streamline the development ...

**Comment by annapasca** [comment]
> @annapasca do you want to try this? It would really streamline the development ...

ok! I'll look at it asap!

**Comment by jasmainak** [comment]
Works now!
