### ISSUE TITLE
Epoching node is broken.

### ISSUE THREAD

**Issue by dmalt** [neuropycon/ephypype#63]
After style changes in code epoching stopped working.
This happens because in `preproc._create_epochs`  the  `Epochs` constructor call was substituted with `read_epochs` function, presumably by accident: 
https://github.com/neuropycon/ephypype/blob/68976ee9bf06b76d11b9aaf09b96a3e4e6a70fd8/ephypype/preproc.py#L11
https://github.com/neuropycon/ephypype/blob/68976ee9bf06b76d11b9aaf09b96a3e4e6a70fd8/ephypype/preproc.py#L410-L412

It used to be Epochs instead of read_epochs in both cases.

**Comment by annapasca** [comment]
Hi @dmalt , you can fix it! and yes it was a mistake, sorry for this.

@jasmainak when you talk about test, do u mean unit test, since all these functions are private. I'm a bit confusing about test...thks!

**Comment by jasmainak** [comment]
yep unit testing. You should still have public functions that are your "units" I suppose ...
