### ISSUE TITLE
add folder to circleci

### ISSUE THREAD

**Issue by annapasca** [neuropycon/ephypype#65]
How can I add a folder to circleci?
In particular I have to add the `sample_omega_bids/FSF` folder. I have already updated the Dropbox files.

Thks!

**Comment by jasmainak** [comment]
you shouldn't have to do anything. It should download on it's own. Since we don't cache the data directory.

**Comment by annapasca** [comment]
> you shouldn't have to do anything. It should download on it's own. Since we don't cache the data directory.

it seems there is no dir (see [here](https://github.com/neuropycon/ephypype/pull/64#issuecomment-434780420))

**Comment by annapasca** [comment]
Hi @jasmainak , how can I check the content of `/home/circleci/project/examples/sample_BIDS_omega` ?

I moved the anatomy of `sub-0003` at upper level in the new folder `fsf` and I'd wanted to be sure that inside `/sub-0003/ses-0001/anat` there is only the `.nii` file

Thks!!!

**Comment by jasmainak** [comment]
@annapasca, you can debug using ssh: https://circleci.com/docs/2.0/ssh-access-jobs/

or you can put a statement in `.circleci` to print the directory structure of the folder in question (to be removed before merging)
