### ISSUE TITLE
import_data

### ISSUE THREAD

**Issue by annapasca** [neuropycon/ephypype#82]
In [import_data](https://github.com/neuropycon/ephypype/blob/master/ephypype/import_data.py#L198) there are 4 functions doing more or less the same action. Can I put all in a unique function? 
These are the 4 functions:

Up to now only [_import_tsmat_to_ts](https://github.com/neuropycon/ephypype/blob/0c6038576b10c1c4302fd53b99567252805320f7/ephypype/import_data.py#L123) is used by a Node.

[import_mat_to_conmat](https://github.com/neuropycon/ephypype/blob/0c6038576b10c1c4302fd53b99567252805320f7/ephypype/import_data.py#L83)

[_import_tsmat_to_ts](https://github.com/neuropycon/ephypype/blob/0c6038576b10c1c4302fd53b99567252805320f7/ephypype/import_data.py#L123)

[import_amplmat_to_ts](https://github.com/neuropycon/ephypype/blob/0c6038576b10c1c4302fd53b99567252805320f7/ephypype/import_data.py#L162)

[import_mat_to_ts](https://github.com/neuropycon/ephypype/blob/0c6038576b10c1c4302fd53b99567252805320f7/ephypype/import_data.py#L198)

**Comment by davidmeunier79** [comment]
Yes it seems fair, I do not remember where all these functions came from, but I believe they were related to the origin of the matlab timeseries or matrix, i.e. depending on how they were calculated. 

* import_mat_to_conmat means the matlab file already contains a matrix, computed outside (with brainstorm or else)

* import_mat_to_conmat is when the "good channels" is a field within the matlab structure
* import_amplmat_to_ts is the same as _import_mat_to_ts it seems, so can be removed
* import_mat_to_ts seems a bit different, as the 'good_channels is based on the name of the strings in channel_names (EMG_ and EOG), I do not remember when it is used.

I have remove import_amplmat_to_ts, and merged import_mat_to_ts with _import_mat_to_ts (not implemented for the node, however...). I have renamed  import_mat_to_conmat  -> _import_mat_to_conmat and kept it, but is not used in node structure yet.

PR is here: https://github.com/neuropycon/ephypype/compare/master...davidmeunier79:merge_import_data?expand=1

**Comment by annapasca** [comment]
> Yes it seems fair, I do not remember where all these functions came from, but I believe they were related to the origin of the matlab timeseries or matrix, i.e. depending on how they were calculated.
> 
>     * import_mat_to_conmat means the matlab file already contains a matrix, computed outside (with brainstorm or else)
> 
>     * import_mat_to_conmat is when the "good channels" is a field within the matlab structure
> 
>     * import_amplmat_to_ts is the same as _import_mat_to_ts it seems, so can be removed
> 
>     * import_mat_to_ts seems a bit different, as the 'good_channels is based on the name of the strings in channel_names (EMG_ and EOG), I do not remember when it is used.
> 
> 
> I have remove import_amplmat_to_ts, and merged import_mat_to_ts with _import_mat_to_ts (not implemented for the node, however...). I have renamed import_mat_to_conmat -> _import_mat_to_conmat and kept it, but is not used in node structure yet.
> 
> PR is here: #83

Hi David,

yes, I also thought it was something related to some thing of the past.
Thks for the PR.

I have some comments I'll write there.

**Comment by annapasca** [comment]
> On a side note: isn't it better to have a directory tests in each of the subdirectories where the tests functions or nodes are?

Absolutely yes! in #81 I put the test of nodes, interfaces in the a folder "tests" that is a subdir of nodes, interfaces, ...

**Comment by davidmeunier79** [comment]
> > On a side note: isn't it better to have a directory tests in each of the subdirectories where the tests functions or nodes are?
> 
> Absolutely yes! in #81 I put the test of nodes, interfaces in the a folder "tests" that is a subdir of nodes, interfaces, ...
OK I will do a merge of this version once accepted, and hopefully if will the coverage issue in https://github.com/neuropycon/ephypype/pull/83

**Comment by annapasca** [comment]
close in #83
